name: onetrust_publishers_native_cmp
description: Add the OneTrust native CMP to your Flutter project.
version: 6.28.0
homepage: https://onetrust.com

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.onetrust.flutter.otpublishersnativesdk.onetrust_publishers_native_cmp
        pluginClass: OneTrustPublishersNativeCmpPlugin
      ios:
        pluginClass: OneTrustPublishersNativeCmpPlugin

